name: Build and Publish NPM Package

on:
  pull_request:
    branches:
      - develop
      - main
      - master
    types:
      - opened
      - reopened
      - synchronize
      - closed

env:
  NODE_VERSION: 16

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run build
        env:
          PUBLIC_URL: '/'
          REACT_APP_AUTH_SERIVCE_URL: 'https://ci-europa.kbase.us/services/auth'
        run: npm install && npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: static-ui-build
          path: build/
  build-develop-open:
    if: github.base_ref == 'develop' && github.event.pull_request.merged == false
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: static-ui-build
          path: build
      - name: Reusable Build
        uses: kbase/.github/.github/workflows/reusable_build.yml@main
        secrets: inherit
  build-develop-merge:
    if: github.base_ref == 'develop' && github.event.pull_request.merged == true
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: static-ui-build
          path: build
      - name: Build & Push - Develop
        uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
        with:
          name: '${{ github.event.repository.name }}-develop'
          tags: pr-${{ github.event.number }},latest
          secrets: inherit
#  build-main-open:
#    if: (github.base_ref == 'main' || github.base_ref == 'master') && github.event.pull_request.merged == false
#    uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
#    with:
#      name: '${{ github.event.repository.name }}'
#      tags: pr-${{ github.event.number }}
#    secrets: inherit
#  build-main-merge:
#    if: (github.base_ref == 'main' || github.base_ref == 'master') && github.event.pull_request.merged == true
#    uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
#    with:
#      name: '${{ github.event.repository.name }}'
#      tags: pr-${{ github.event.number }},latest-rc
#    secrets: inherit
#  trivy-scans:
#    if: (github.base_ref == 'develop' || github.base_ref == 'main' || github.base_ref == 'master' ) && github.event.pull_request.merged == false
#    uses: kbase/.github/.github/workflows/reusable_trivy-scans.yml@main
#    secrets: inherit
